// frontend/src/components/InstallBanner.svelte
<script lang="ts">
  let visible = $state(true);
</script>

{#if visible}
  <div class="pointer-events-none fixed inset-x-0 bottom-0 z-40 flex justify-center px-4 pb-[calc(env(safe-area-inset-bottom)+1rem)]">
    <div class="pointer-events-auto flex w-full max-w-md items-center gap-2.5 rounded-full border border-border bg-card/95 py-2 pl-3 pr-2 shadow-xl shadow-black/30 backdrop-blur">
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="shrink-0 text-primary">
        <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/>
      </svg>
      <p class="min-w-0 flex-1 truncate text-sm">
        <span class="font-medium">Instalá la app</span>
        <span class="text-muted-foreground"> para acceso rápido</span>
      </p>
      <button class="shrink-0 rounded-full bg-primary px-3 py-1.5 text-xs font-medium text-primary-foreground transition-transform hover:scale-105 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-ring">
        Instalar
      </button>
      <button
        class="flex h-7 w-7 shrink-0 items-center justify-center rounded-full text-muted-foreground transition-colors hover:text-foreground focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-ring"
        onclick={() => visible = false}
        aria-label="Descartar"
      >
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
          <line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/>
        </svg>
      </button>
    </div>
  </div>
{/if}

// pomodoro-timer/components/install-banner.tsx
'use client'

import { useState } from 'react'
import { Download, X } from 'lucide-react'

export function InstallBanner() {
  const [visible, setVisible] = useState(true)

  if (!visible) return null

  return (
    <div className="pointer-events-none fixed inset-x-0 bottom-0 z-40 flex justify-center px-4 pb-[calc(env(safe-area-inset-bottom)+1rem)]">
      <div className="pointer-events-auto flex w-full max-w-md items-center gap-2.5 rounded-full border border-border bg-card/95 py-2 pl-3 pr-2 shadow-xl shadow-black/30 backdrop-blur">
        <Download className="h-4 w-4 shrink-0 text-primary" />
        <p className="min-w-0 flex-1 truncate text-sm">
          <span className="font-medium">Instalá la app</span>{' '}
          <span className="text-muted-foreground">para acceso rápido</span>
        </p>
        <button className="shrink-0 rounded-full bg-primary px-3 py-1.5 text-xs font-medium text-primary-foreground transition-transform hover:scale-105 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-ring">
          Instalar
        </button>
        <button
          onClick={() => setVisible(false)}
          aria-label="Descartar"
          className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full text-muted-foreground transition-colors hover:text-foreground focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-ring"
        >
          <X className="h-4 w-4" />
        </button>
      </div>
    </div>
  )
}
